all:  prog18 prog19 prog20 prog21 prog22 prog23 prog24 prog25 prog26 prog27 prog28 prog29 prog30	



prog18: 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/01_sklearnex_Intro_Speedups.ipynb
	echo prog18; jupyter nbconvert --to script 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/01_sklearnex_Intro_Speedups.ipynb
	mv 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/01_sklearnex_Intro_Speedups.py 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/01_sklearnex_Intro_Speedups.ipy
	cd 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/; ipython 01_sklearnex_Intro_Speedups.ipy
	

prog19: 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/02_CoarsePatchingSVM_Notebook.ipynb
	echo prog19; jupyter nbconvert --to script 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/02_CoarsePatchingSVM_Notebook.ipynb
	mv 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/02_CoarsePatchingSVM_Notebook.py 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/02_CoarsePatchingSVM_Notebook.ipy
	cd 01_Introduction_to_Intel_Extensions_for_Scikit-learn_Patching_CPU/solution/; ipython 02_CoarsePatchingSVM_Notebook.ipy
	

prog20: 02_Applied_Patching_CPU/solution/01_Pairwise_DistanceVectorizedStockSImulation.ipynb
	echo prog20; jupyter nbconvert --to script 02_Applied_Patching_CPU/solution/01_Pairwise_DistanceVectorizedStockSImulation.ipynb
	mv 02_Applied_Patching_CPU/solution/01_Pairwise_DistanceVectorizedStockSImulation.py 02_Applied_Patching_CPU/solution/01_Pairwise_DistanceVectorizedStockSImulation.ipy
	cd 02_Applied_Patching_CPU/solution/; ipython 01_Pairwise_DistanceVectorizedStockSImulation.ipy
	

prog21: 02_Applied_Patching_CPU/solution/02_sklearnex_Kmeans.ipynb
	echo prog21; jupyter nbconvert --to script 02_Applied_Patching_CPU/solution/02_sklearnex_Kmeans.ipynb
	mv 02_Applied_Patching_CPU/solution/02_sklearnex_Kmeans.py 02_Applied_Patching_CPU/solution/02_sklearnex_Kmeans.ipy
	cd 02_Applied_Patching_CPU/solution/; ipython 02_sklearnex_Kmeans.ipy
	

prog22: 03_Applied_to_Image_Clustering_CPU/solution/01_Practicum_ImageClustering.ipynb
	echo prog22; jupyter nbconvert --to script 03_Applied_to_Image_Clustering_CPU/solution/01_Practicum_ImageClustering.ipynb
	mv 03_Applied_to_Image_Clustering_CPU/solution/01_Practicum_ImageClustering.py 03_Applied_to_Image_Clustering_CPU/solution/01_Practicum_ImageClustering.ipy
	cd 03_Applied_to_Image_Clustering_CPU/solution/; ipython 01_Practicum_ImageClustering.ipy
	

prog23: 04_Applied_to_Galaxy_Classification_CPU/solution/Practicum_AnalyzeGalaxyBatch.ipynb
	echo prog23; jupyter nbconvert --to script 04_Applied_to_Galaxy_Classification_CPU/solution/Practicum_AnalyzeGalaxyBatch.ipynb
	mv 04_Applied_to_Galaxy_Classification_CPU/solution/Practicum_AnalyzeGalaxyBatch.py 04_Applied_to_Galaxy_Classification_CPU/solution/Practicum_AnalyzeGalaxyBatch.ipy
	cd 04_Applied_to_Galaxy_Classification_CPU/solution/; ipython Practicum_AnalyzeGalaxyBatch.ipy
	

prog24: 05_Introduction_dpctl_for_GPU/solution/01_Introduction_simple_gallery_dpctl_for_GPU_Solution.ipynb
	echo prog24; jupyter nbconvert --to script 05_Introduction_dpctl_for_GPU/solution/01_Introduction_simple_gallery_dpctl_for_GPU_Solution.ipynb
	mv 05_Introduction_dpctl_for_GPU/solution/01_Introduction_simple_gallery_dpctl_for_GPU_Solution.py 05_Introduction_dpctl_for_GPU/solution/01_Introduction_simple_gallery_dpctl_for_GPU_Solution.ipy
	cd 05_Introduction_dpctl_for_GPU/solution/; ipython 01_Introduction_simple_gallery_dpctl_for_GPU_Solution.ipy
	

prog25: 05_Introduction_dpctl_for_GPU/solution/02_PatchingKNN_GPU_Solution.ipynb
	echo prog25; jupyter nbconvert --to script 05_Introduction_dpctl_for_GPU/solution/02_PatchingKNN_GPU_Solution.ipynb
	mv 05_Introduction_dpctl_for_GPU/solution/02_PatchingKNN_GPU_Solution.py 05_Introduction_dpctl_for_GPU/solution/02_PatchingKNN_GPU_Solution.ipy
	cd 05_Introduction_dpctl_for_GPU/solution/; ipython 02_PatchingKNN_GPU_Solution.ipy
	

prog26: 05_Introduction_dpctl_for_GPU/solution/03_Gallery_of_Functions_on_GPU_Solution.ipynb
	echo prog26; jupyter nbconvert --to script 05_Introduction_dpctl_for_GPU/solution/03_Gallery_of_Functions_on_GPU_Solution.ipynb
	mv 05_Introduction_dpctl_for_GPU/solution/03_Gallery_of_Functions_on_GPU_Solution.py 05_Introduction_dpctl_for_GPU/solution/03_Gallery_of_Functions_on_GPU_Solution.ipy
	cd 05_Introduction_dpctl_for_GPU/solution/; ipython 03_Gallery_of_Functions_on_GPU_Solution.ipy
	

prog27: 06_Applied_to_Image_Clustering_GPU/solution/01_Practicum_ImageClustering_Solution.ipynb
	echo prog27; jupyter nbconvert --to script 06_Applied_to_Image_Clustering_GPU/solution/01_Practicum_ImageClustering_Solution.ipynb
	mv 06_Applied_to_Image_Clustering_GPU/solution/01_Practicum_ImageClustering_Solution.py 06_Applied_to_Image_Clustering_GPU/solution/01_Practicum_ImageClustering_Solution.ipy
	cd 06_Applied_to_Image_Clustering_GPU/solution/; ipython 01_Practicum_ImageClustering_Solution.ipy
	

prog28: 07_Applied_to_Galaxy_Classification_GPU/solution/Practicum_AnalyzeGalaxyBatch_Solution.ipynb
	echo prog28; jupyter nbconvert --to script 07_Applied_to_Galaxy_Classification_GPU/solution/Practicum_AnalyzeGalaxyBatch_Solution.ipynb
	mv 07_Applied_to_Galaxy_Classification_GPU/solution/Practicum_AnalyzeGalaxyBatch_Solution.py 07_Applied_to_Galaxy_Classification_GPU/solution/Practicum_AnalyzeGalaxyBatch_Solution.ipy
	cd 07_Applied_to_Galaxy_Classification_GPU/solution/; ipython Practicum_AnalyzeGalaxyBatch_Solution.ipy
	

prog29: 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/01_Numpy_How_Fast_Are_Numpy_Ops_SOLUTION.ipynb
	echo prog29; jupyter nbconvert --to script 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/01_Numpy_How_Fast_Are_Numpy_Ops_SOLUTION.ipynb
	mv 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/01_Numpy_How_Fast_Are_Numpy_Ops_SOLUTION.py 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/01_Numpy_How_Fast_Are_Numpy_Ops_SOLUTION.ipy
	cd 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/; ipython 01_Numpy_How_Fast_Are_Numpy_Ops_SOLUTION.ipy
	

prog30: 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/02_PandasPoweredBy_oneAPI_SOLUTION.ipynb
	echo prog30; jupyter nbconvert --to script 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/02_PandasPoweredBy_oneAPI_SOLUTION.ipynb
	mv 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/02_PandasPoweredBy_oneAPI_SOLUTION.py 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/02_PandasPoweredBy_oneAPI_SOLUTION.ipy
	cd 08_Introduction_to_Numpy_powered_by_oneAPI/solutions/; ipython 02_PandasPoweredBy_oneAPI_SOLUTION.ipy
